### ISSUE TITLE
Update to new atom API

### ISSUE THREAD

**Issue by ozkxr** [heroicyang/atom-hexo#7]
Here are 2 `deprecated` alerts thrown by atom:

* Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `atom-hexo` package
* Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows:

 ```
"activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```

**Comment by heroicyang** [comment]
Updated :smile:

**Comment by ozkxr** [comment]
Great :) :+1:
